---
- hosts: localhost
  gather_facts: no

  vars:
#    tower_server: tower01.shadow
    tower_server: 10.0.20.193
    tower_user: admin
    tower_pass: GoKEV!
    tower_action: backup
#    tower_action: restore


  roles:
    - "GoKEV-tower-{{ tower_action }}"

