---
## tasks file for GoKEV-tower-backup
## Here we will loop through these included tasks
## Credentials
## Projects
## Job Templates
## Local Users
## Inventories

- name: register all job template details
  uri:
    url: "https://{{ tower_url }}api/v2/job_templates/"
    method: GET
    user: "{{ tower_user }}"
    password: "{{ tower_pass }}"
    force_basic_auth: yes
    status_code: 200
    validate_certs: False
    return_content: yes
  register: all_templates

- set_fact:
    all_templates: "{{ all_templates.json.results | map(attribute='name') | list }}"

- debug:
    msg: "{{ item }}"
  with_items: "{{ all_templates }}"

- command: "tower-cli receive -p {{ tower_pass }} -u {{ tower_user }} -h https://{{ tower_url }} --insecure --job_template {{ item }}"
  with_items: "{{ all_templates }}"
  register: output

- debug:
    var: output

